project:
  type: website

website:
  title: "QuantBender"
  navbar:
    right:
      - about.qmd
      - blogs.qmd
      - projects.qmd
      - cheat_sheets.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/desire_dosseh
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: source
comments:
  giscus:
    repo:  quantbender/quantbender.github.io
    repo-id: "R_kgDOPamaAQ"
    category: "Announcements"
    category-id: "DIC_kwDOPamaAc4CvEiP"
    mapping: "pathname"
    reactions-enabled: true
    loading: lazy
    input-position: "bottom"
    theme: "light"
